window.PORTFOLIO = {
 stations: [
  {eye:'01 / HELLO, WORLD',title:"Hi, I'm<br><em>Hubery.</em>",subtitle:'朱果 · 研究者 / 开发者 / 玩家',description:'探索人、AI 与游戏之间的可能性。<br>把研究问题，做成可以体验的交互。',tags:['HCI','AI AGENT','UNITY / VR'],action:'认识我',detail:'about',label:'HELLO WORLD',color:'#c1f99a'},
  {eye:'02 / THE HCI LAB',title:'从人的问题，<br><em>开始设计。</em>',subtitle:'人机交互 · 参与式设计 · VR',description:'理解真实需求，再构建可体验的系统。<br>探索牙科场景中的 AI 与虚拟现实。',tags:['HUMAN-CENTERED','UNITY','QUEST 3'],action:'查看 HCI 项目',detail:'hci',label:'HCI LAB',color:'#9bdee7'},
  {eye:'03 / THE AI LAB',title:'听懂对话，<br><em>也理解情境。</em>',subtitle:'多轮语音评测 · 可控语音生成',description:'从评测基准到语音生成，<br>探索更自然的人与 AI 对话。',tags:['PYTHON','PYTORCH','SPEECH AI'],action:'查看 AI 项目',detail:'ai',label:'AI LAB',color:'#bab4ff'},
  {eye:'04 / THE GAME STUDIO',title:'把一个想法，<br><em>变成可玩。</em>',subtitle:'Unity / C# · 游戏原型 · Game Jam',description:'让机制回应玩家的操作。<br>用原型、试玩与迭代验证设计。',tags:['UNITY / C#','GAME JAM','PROTOTYPING'],action:'查看游戏经历',detail:'game',label:'GAME STUDIO',color:'#f5be8d'},
  {eye:'05 / THE NEXT CHAPTER',title:'下一段旅程，<br><em>一起创造。</em>',subtitle:'寻找 AI / 游戏方向实习',description:'期待参与游戏 AI、Agent 与 AI 应用，<br>把研究洞察转化为实际体验。',tags:['AI AGENT','AI APPLICATIONS','GAME DEV'],action:'联系方式',detail:'contact',label:'SAY HELLO',color:'#c1f99a'}
 ], details:{}, resume:''
};
const external = (href,label) => `<a href="${href}" target="_blank" rel="noopener noreferrer">${label}</a>`;
const metrics = rows => `<div class="detail-metrics">${rows.map(([value,label])=>`<div><strong>${value}</strong><span>${label}</span></div>`).join('')}</div>`;
const links = rows => `<div class="detail-links">${rows.map(([href,label])=>external(href,label)).join('')}</div>`;
PORTFOLIO.details = {
 about:{eye:'01 / RESEARCHER · BUILDER · PLAYER',title:'你好，我是朱果 / Hubery。',html:`<p class="lead">香港中文大学（深圳）人工智能 MPhil 在读。我关注 HCI、语音模型评测与生成，也用 Unity 构建 VR 交互系统与游戏原型。</p><p class="lead">我希望把对人的理解、AI 的能力与游戏的可玩性连接起来，寻找游戏 AI / Agent 开发及 AI 应用方向的实习机会。日常实习优先，近期可入职。</p><h3>从研究，到可以亲手体验的系统</h3><ul><li>研究：参与式设计、用户研究、模型评测与可控语音生成。</li><li>开发：Unity / C#、Quest 3、Python / PyTorch，完成原型、数据处理与评测。</li><li>玩家视角：长期体验 FPS、MOBA、Roguelike 与空间解谜，关注机制与反馈如何塑造体验。</li></ul>${links([['assets/Hubery-CV.pdf','PDF 简历'],['https://github.com/HuberyGG','GitHub'],['https://scholar.google.com/citations?user=Okxt8dgAAAAJ&hl=en','Google Scholar'],['https://space.bilibili.com/35953087','B 站 · Hu6ery']])}`},
 hci:{eye:'02 / HUMAN–COMPUTER INTERACTION',title:'让人拥有更多理解与掌控。',html:`<p class="lead">在牙科情境中，探索 VR 如何支持焦虑体验；在医学教学中，参与设计能回应实际需求的 AI 标准化病人。</p><h3>牙科焦虑干预 VR 系统</h3><p class="lead">2026.04–2026.09 · 系统开发 / 论文第一作者</p>${metrics([['Unity','Quest 3 交互系统'],['5 类','事件触发场景'],['24 人','随机研究']])}<ul><li>结合 36 人调研、3 名牙医共创与 12 名患者走查，实现呼吸引导、感官减弱、虚拟陪伴与暂停控制。</li><li>结合焦虑评分、生理信号与访谈评估系统。模拟场景中，焦虑评分调整后组间差异为 −12.83 分（0–100 分量表）。</li></ul><p class="paper-meta">研究状态：arXiv 预印本；CHI 2027 已投稿。上述结果来自模拟场景研究。</p>${links([['https://arxiv.org/abs/2609.15867','阅读 VR 预印本']])}<h3>Co-Designing AI Standardized Patients</h3><ul><li>参与 12 名医学生访谈、3 场共创工作坊，分析并提炼 6 类需求与 6 项设计要求。</li><li>第一作者成果，已发表于 CHI 2026 Extended Abstracts。</li></ul>${links([['https://doi.org/10.1145/3772363.3798336','查看 CHI EA 论文']])}`},
 ai:{eye:'03 / SPEECH & ARTIFICIAL INTELLIGENCE',title:'从理解对话，到生成声音。',html:`<p class="lead">把模型能力拆解为可评测的问题，也把复杂语音场景转化为可生成、可检查的数据。</p><h3>MTalk-Bench · 多轮语音理解评测</h3><p class="paper-meta">2025.03–2025.08 · 研究成员 / 论文第二作者</p>${metrics([['9 类','评测场景'],['270 段','评测对话'],['Arena','结合 Rubrics 评分']])}<ul><li>参与制作、筛选真人录音、合成语音与环境音，构建多轮语音理解评测数据。</li><li>参与模型部署与评测，分析语义、副语言、环境音理解，以及 LLM 评审的位置与长度偏差。</li></ul>${links([['https://arxiv.org/abs/2508.18240','阅读 MTalk-Bench 预印本']])}<h3>MedTTS · 可控病理语音生成</h3><p class="paper-meta">2025.12–至今 · 核心研究成员</p>${metrics([['8 位','克隆说话人'],['25 小时','生成语音'],['6,200 条','语音数据']])}<ul><li>使用 Qwen3-TTS-1.7B 生成数据，融合真实声音，完成事件插入、淡入淡出与响度对齐。</li><li>以 Qwen3.5-Omni 进行自动标注与质检，参与 LLM–Flow Matching 模型研究与 DPO 优化。</li></ul><p class="paper-meta">进行中的研究项目。</p>`},
 game:{eye:'04 / DESIGN · BUILD · PLAYTEST',title:'让操作本身，也成为谜题。',html:`<p class="lead">我喜欢游戏里“原来还能这样”的瞬间，也尝试用关卡、交互规则与反馈把它做出来。</p><h3>What's behind the door · 毕业设计</h3><p class="lead">使用 Unity 制作的第一人称恐怖解谜毕业设计。玩家在不断循环的走廊中探索，逐步揭示背后的故事；灵感来自《寂静岭：PT》。</p><img class="portfolio-preview" src="assets/whats-behind-the-door.jpg" alt="毕业设计 Demo 的游戏画面" loading="lazy">${links([['https://www.bilibili.com/video/BV1LcApepE9x/','观看毕业设计 Demo · 12 分钟']])}<h3>Esecret · Game Off 2024</h3><p class="paper-meta">2024.11–2024.12 · 独立设计与开发</p><ul><li>围绕 Secret 主题，把 ESC 设置与游戏世界变化关联，让玩家通过重试关卡发现线索、解决跨关卡逻辑谜题。</li><li>用 Unity / C# 完成关卡白盒、交互逻辑与谜题流程，整合美术资源，完成游戏打包与测试。</li></ul><div class="station-tags"><span>UNITY / C#</span><span>PUZZLE DESIGN</span><span>GAME JAM</span></div><h3>Struct Game Studio · 游戏设计实习</h3><p class="paper-meta">吉隆坡 · 2024.08–2024.10</p><ul><li>围绕跨文化主题完成 3 个关卡的调研、机制与流程设计，编写策划案并跟进制作人评审迭代。</li><li>开发、测试计算机视觉解谜原型，验证玩法与流程。</li></ul><h3>早期创作 · 本科作品集</h3><p class="lead">从《逃离荷鲁斯金字塔》合作策略桌游，到 Let's Recycle! 交互原型，再到《无翼鸟》《灯笼山》动画，探索不同媒介中的交互与叙事。</p><img class="portfolio-preview" src="assets/horus-boardgame-photo.jpg" alt="逃离荷鲁斯金字塔的实体桌游" loading="lazy"><p class="portfolio-caption">《逃离荷鲁斯金字塔》· 本科作品集</p>${links([['assets/Hubery-Portfolio.pdf','查看本科作品集 · 14 MB']])}<h3>不止制作，也一直在玩</h3><p class="lead">FPS / MOBA 累计 3,500+ 小时；也长期体验卡组构筑、Roguelike、空间解谜与剧情动作游戏。从《杀戮尖塔》到《传送门》，关注不同系统如何让玩家学习与探索。</p>${links([['https://space.bilibili.com/35953087','访问 B 站 · Hu6ery']])}`},
 contact:{eye:'05 / LET’S BUILD SOMETHING',title:'一起做些有意思的事。',html:`<p class="lead">寻找游戏 AI / Agent、AI 应用开发与交互研发方向的实习，也关注 AI 技术产品机会。日常实习优先，近期可入职。</p><h3>联系我</h3><a class="contact-line" href="mailto:guo176797@gmail.com">guo176797@gmail.com</a><p class="lead" style="margin-top:22px">如果你正在寻找一位能从用户问题出发、参与 AI 研究，也能动手搭建 Unity 交互原型的伙伴，欢迎交流。</p>${links([['assets/Hubery-CV.pdf','查看 PDF 简历'],['https://github.com/HuberyGG','GitHub'],['https://scholar.google.com/citations?user=Okxt8dgAAAAJ&hl=en','Google Scholar'],['https://space.bilibili.com/35953087','B 站 · Hu6ery']])}`}
};

PORTFOLIO.details.early = {eye:'EARLY EXPLORATIONS / UNDERGRADUATE WORK',title:'让想法在不同媒介里生长。',html:`<p class="lead">本科阶段的作品集，记录了从游戏规则、动画叙事到交互界面的探索。以下为早期课程作品。</p><h3>逃离荷鲁斯金字塔 · 合作策略桌游</h3><p class="lead">面向 4 名玩家与 1 名主持人的限时逃脱桌游，结合合作解谜、战斗与钥匙收集。</p><img class="portfolio-preview" src="assets/horus-boardgame-photo.jpg" alt="逃离荷鲁斯金字塔实体桌游"><p class="portfolio-caption">本科作品集，第 6–8 页。</p><h3>Let's Recycle! · Figma 交互原型</h3><p class="lead">面向垃圾回收教育的中保真原型，探索通过交互流程帮助用户学习垃圾分类与回收。</p><img class="portfolio-preview" src="assets/lets-recycle-prototype.png" alt="Let's Recycle 原型界面" loading="lazy"><p class="portfolio-caption">本科作品集，第 16–17 页。</p><h3>动画叙事 · Adobe Animate</h3><ul><li>《无翼鸟》：1 分 01 秒的小组课程短片，包含逐帧动画、补间与播放交互。</li><li>《灯笼山》：2 分 18 秒的小组课程短片，围绕梦想、离别与重逢展开叙事。</li></ul>${links([['assets/Hubery-Portfolio.pdf','查看完整本科作品集 · 14 MB']])}`};
